### ISSUE TITLE
does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by nnothing1** [cqjjjzr/Aegisub-Conan-CMake#1]
Is the cmakelist.txt file missing?

**Comment by cqjjjzr** [comment]
In this repo, no CMakeLists.txt is needed. What you need to do is simply set the path to the `dependencies_conan.cmake` as the `DEPENDENCIES_CMAKE_FILE` varible of CMake when building Aegisub. And CMakeLists.txt is in the Aegisub repository.

**Comment by nnothing1** [comment]
thank you，But I still encounter some errors.
ERROR: Unable to find 'libass/0.14.0@charliejiang/stable' in remotes
CMake Error at H:/Aegisub-master/Aegisub-Conan-CMake/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  H:/Aegisub-master/Aegisub-Conan-CMake/conan.cmake:480 (conan_cmake_install)
  H:/Aegisub-master/Aegisub-Conan-CMake/dependencies_conan.cmake:147 (conan_cmake_run)
  CMakeLists.txt:183 (include)

**Comment by cqjjjzr** [comment]
This is one of the weird problem I observed today.

Although I wrote those in the cmake file:
```cmake
conan_add_remote(NAME bincrafters URL https://api.bintray.com/conan/bincrafters/public-conan)
conan_add_remote(NAME charliejiang URL https://api.bintray.com/conan/charliejiang/conan)
conan_add_remote(NAME h4mster URL https://api.bintray.com/conan/h4mster/conan)
```
But them seem not to be added. Before I resolve this you can manually do this in the command line:
```shell
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
conan remote add charliejiang https://api.bintray.com/conan/charliejiang/conan
conan remote add h4mster https://api.bintray.com/conan/h4mster/conan
```

**Comment by nnothing1** [comment]
This error is encountered every time during the build. Is this a bug or a mistake in my operation?
Thanks

icu/64.2@bincrafters/stable: Not rebuilding data/rules.mk, assuming prebuilt data in data/in
icu/64.2@bincrafters/stable: Spawning Python to generate test/testdata/rules.mk...
icu/64.2@bincrafters/stable: ../source//configure: line 9141: /c/Users/10542/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
icu/64.2@bincrafters/stable: configure: error: Python failed to run; see above error.
icu/64.2@bincrafters/stable: ../source/runConfigureICU: ./configure failed
icu/64.2@bincrafters/stable:
CMake Error at H:/Aegisub-master/Aegisub-Conan-CMake/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  H:/Aegisub-master/Aegisub-Conan-CMake/conan.cmake:480 (conan_cmake_install)
  H:/Aegisub-master/Aegisub-Conan-CMake/dependencies_conan.cmake:147 (conan_cmake_run)
  CMakeLists.txt:183 (include)

**Comment by cqjjjzr** [comment]
I think it's because you don't have a proper Python3 Installation. Install the latest Python 3.7 and configure the PATH environment varible.

**Comment by nnothing1** [comment]
After I reinstalled Python. All dependencies are properly installed. thank you for your generous  help
